repos:

- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.6.2
  hooks:
    # Run the linter.
    - id: ruff
      # don't autofix by default, this runs in CI
      # to run fix locally, use `ruff check src/ --fix`
      # args: [ --fix ]
    # Run the formatter.
    - id: ruff-format
