# This is an example file for configuring the Halmos settings.
# For configuration values, refer to the options listed under the 'halmos --help' command.

# for now, every setting must be under the 'global' section
[global]

verbose = 3
debug = true
statistics = true

depth = 1_000_000
storage-layout = 'generic'
