[profile.default]
src = 'src'
out = 'out'
libs = ["../../tests/lib", 'lib']

evm_version = 'cancun'

force = false
# compile options used by halmos (to prevent unnecessary recompilation when running forge test and halmos together)
extra_output = ["storageLayout", "metadata"]
