# https://docs.github.com/en/copilot/customizing-copilot/customizing-the-development-environment-for-copilot-coding-agent
name: "Copilot Setup Steps"

# Allow testing of the setup steps from your repository's "Actions" tab.
on: workflow_dispatch

jobs:
  # The job MUST be called `copilot-setup-steps` or it will not be picked up by Copilot.
  copilot-setup-steps:
    runs-on: ubuntu-latest

    # Copilot will be given its own token for its operations.
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          # let's use the oldest version of python that is supported by the project
          python-version: "3.11"

      - name: Install foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          version: "0.5.21"

      - name: Install halmos and its dependencies
        run: uv sync --extra dev
