name: Publish to PyPI
on:
  release:
    types: [published]
jobs:
  pypi:
    runs-on: ubuntu-latest
    environment: release
    permissions:
      # IMPORTANT: this permission is mandatory for Trusted Publishing
      # https://docs.pypi.org/trusted-publishers/using-a-publisher/
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Build
        run: python3 -m pip install --upgrade build && python3 -m build
      - name: Publish
        uses: pypa/gh-action-pypi-publish@release/v1

